# Generated by Django 4.0.2 on 2022-02-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=500)),
                ('time_register', models.DateTimeField(auto_now_add=True)),
                ('time_last_game', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to='game.user')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to='game.user')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='game.user')),
            ],
        ),
    ]
