# Generated by Django 4.0.2 on 2022-02-08 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterField(
            model_name='games',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
