# Generated by Django 4.0.2 on 2022-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_waitinggame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinggame',
            options={'verbose_name': 'Игра в ожидании', 'verbose_name_plural': 'Игры в ожидании'},
        ),
        migrations.AddField(
            model_name='games',
            name='href_name',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
