# Generated by Django 4.0.2 on 2022-02-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_alter_games_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='first',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='first', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
