# Generated by Django 4.0.2 on 2022-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_games_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='field',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
