# Generated by Django 4.0.2 on 2022-02-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_games_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='field',
            field=models.CharField(default='[[0, 0, 0], [0, 0, 0], [0, 0, 0]]', max_length=9),
        ),
    ]
